### ISSUE TITLE
Kernel 6.6 support request

### ISSUE THREAD

**Issue by PhYziCiAN** [remittor/zapret-openwrt#10]
Добрый вечер.
У меня какое-то свежее ядро в роутере Flint 2.
opkg info kernel -> 
Package: kernel
Version: 6.6.47~5f888a243508bd63116c3c6987914d47-r1
Depends: libc
Status: install ok installed
Architecture: aarch64_cortex-a53

Luci -> OpenWrt 24.0 r27229+44-ebe7c5f1a3 / LuCI Master 24.188.41532~d3bf675

На него эти пакеты не встают. 
Вопрос: какие перспективы сборки пакетов под это новомодное ядро?

**Comment by remittor** [comment]
Покажите содержимое вот этих 2-х файликов
/etc/opkg/distfeeds.conf
/etc/opkg/customfeeds.conf

**Comment by PhYziCiAN** [comment]
cat /etc/opkg/distfeeds.conf
src/gz glinet_target https://fw.gl-inet.com/releases/v24.x/v4.6/aarch64_cortex-a53/filogic
src/gz glinet_pub https://fw.gl-inet.com/releases/v24.x/v4.6/aarch64_cortex-a53/glinet
src/gz glinet_openwrt https://fw.gl-inet.com/releases/v24.x/v4.6/aarch64_cortex-a53/packages

root@mt6000:~# cat /etc/opkg/customfeeds.conf
.# add your custom package feeds here
.# src/gz example_feed_name http://www.example.com/path/to/files

**Comment by remittor** [comment]
> На него эти пакеты не встают.

А что за ошибка при установке?

**Comment by PhYziCiAN** [comment]
Вопрос снят. Вероятно, не сдалал opkg update предварительно. Сработала последоватальность команд.
```
opkg update

wget -O - "https://github.com/remittor/zapret-openwrt/releases/download/v67-20241030-23.05/zapret_v67-202
41030_aarch64_cortex-a53.zip" | bsdtar -xvf- -C /mnt/sda1/

cd /mnt/sda1

opkg install *.ipk
```
