### ISSUE TITLE
Ошибка в интерфейсе 

### ISSUE THREAD

**Issue by slayer326** [remittor/zapret-openwrt#18]
Установил по инструкции, перезагрузил роутер (), при нажатии на запрет, получаю ошибку сверху 

`SyntaxError

missing ) after condition
  in https://192.168.1.1/luci-static/resources/view/zapret/tools.js?v=git-24.086.45142-09d5a38:32
  at require/compileClass/< (https://192.168.1.1/luci-static/resources/luci.js?v=git-24.086.45142-09d5a38:179:29)
`

Роутер | Xiaomi Mi Router 4A (100M Edition)

OpenWrt 23.05.4 r24012-d8dd03c46f / LuCI openwrt-23.05 branch git-24.086.45142-09d5a38
![2024-11-10 22_51_54-OpenWrt - LuCI — Mozilla Firefox](https://github.com/user-attachments/assets/5b0b80cc-f1e9-4f8f-a628-3fcab591015c)

**Comment by DEAth1981** [comment]
Аналогично... даже снёс папку /opt/zapret, не помогло... откатился на 67 версию, проблем нет

**Comment by remittor** [comment]
Моя ошибка.
Удалил некорректный релиз.

**Comment by wargano** [comment]
ошибка по прежнему присутствует (на свежем релизе) mipsel 24kc
![Screenshot_2024-11-11-10-21-25-91_2c2851f616de21a6da6fb44c83a25e93](https://github.com/user-attachments/assets/53c4b4f6-9058-452c-a5be-91677cd46310)

**Comment by slayer326** [comment]
Снёс старую версию, поставил v68-20241110 for OpenWrt 23.05. Бага нет, всё отлично работает, спасибо!
