### ISSUE TITLE
Не работает если встроить пакет на стадию сборки прошивки OpenWrt 24

### ISSUE THREAD

**Issue by dvv47** [remittor/zapret-openwrt#19]
Только что решил поставить пакет на роутер banana pi bpi-r4
он только на свежих OpenWrt хорошо работает

Получил ошибки 
Unable to read the service info 
и
LuCI APP v68-20241110-r20241110 [ incorrect version! ]
![image](https://github.com/user-attachments/assets/7e24511d-cdd8-41a2-a1ba-fa5a7ed2aab9)

Сейчас попробую разобраться что ему не нравится

Судя по всему он пробует звать

```
ll /etc/init.d/zapret
-rwxr-xr-x    1 root     root          4702 Nov 10 18:45 /etc/init.d/zapret*
```

Файл на месте и с правильными правами

Попробовал запустить его вручную получил ошибку

```
/etc/init.d/zapret info
/etc/rc.common: .: line 6: can't open '/opt/zapret/config': No such file or directory

```

в папке /opt/zapret файла конфиг действительно нет, может он искал config.default?

Пока попробовал поменять настройки на вкладке settings и применить их, но это не помогло

![image](https://github.com/user-attachments/assets/56cb03f3-edb7-44fd-948c-fb4e37e01dcb)

**Comment by dvv47** [comment]
Дело оказалось в том что я zapret-openwrt установил не через пакетный менеджер, а включил в прошивку
Поэтому не отработала стадия postinst в makefile

**Comment by remittor** [comment]
Да. Этот момент я забыл учесть.
Нужно мне postinst включить в uci-defaults.
Мде ...

**Comment by dvv47** [comment]
> Да. Этот момент я забыл учесть. Нужно мне postinst включить в uci-defaults. Мде ...

я гляну сегодня - завтра вечером, там ведь надо убедится что пользовательские конфиги случайно от переустановки не затрутся. мб в javascript частично перенести

**Comment by remittor** [comment]
В сборке от 20241115 сделал возможным интегрирование в сборку.
Но у вас похоже уже apk...
