### ISSUE TITLE
Обновление версий

### ISSUE THREAD

**Issue by LEECH161** [remittor/zapret-openwrt#20]
Не нашел в инструкции описание обновления.
Например переезд с 67 версии на 68 (установлены 2 обязательных ipk-файла).
Работает ли обновление через System - Software - Updates?

**Comment by remittor** [comment]
Да всех ipk это должно работать! Стандарты openwrt соблюдены!

**Comment by LEECH161** [comment]
> Да всех ipk это должно работать! Стандарты openwrt соблюдены!

Ок, спасибо.
