### ISSUE TITLE
Нужны билды APK

### ISSUE THREAD

**Issue by dabdullin** [remittor/zapret-openwrt#26]
На OpenWRT SNAPSHOT перешли по умолчанию на APK. Необходимы сборки Zapret для APK.

**Comment by mzng-dbl** [comment]
Поддерживаю, есть такое

**Comment by remittor** [comment]
APK файлы уже доступны.
Разработчики OpenWrt ограничили в своих офиц. прошивках установку apk-файлов, которые были скачены с недоверенного источника.
Поэтому через LuCI apk не установить.
Нужно передавать apk файл на внутренний носитель роутера (к примеру в директорию /tmp) и через консольную команду устанавливать apk:
```
apk add  --allow-untrusted   /tmp/zapret-69.20241121.apk
apk add  --allow-untrusted   /tmp/luci-app-zapret-69.20241121-r1.apk
```
Как то так....

**Comment by dabdullin** [comment]
Спасибо, @remittor!
