### ISSUE TITLE
Установил собствено эти пакеты а status undefined 

### ISSUE THREAD

**Issue by chaush-server** [remittor/zapret-openwrt#3]
![изображение](https://github.com/user-attachments/assets/d973cf52-5ce2-461a-864d-93483da772c1)
![изображение](https://github.com/user-attachments/assets/affe04fd-580a-4cb5-bb42-90965b30e9b4)

Может сделаешь гайд, а то мне как совсем хлебушку не разобраться

**Comment by remittor** [comment]
> Может сделаешь гайд, а то мне как совсем хлебушку не разобраться

Так после установки уже должен ютуб "летать". Если изменили настройки, то нажмите restart, что бы они применились.

**Comment by Vaccinator424** [comment]
Та же история, статус undefined, ютуб не пашет
![Screenshot_3](https://github.com/user-attachments/assets/5ccf4173-447d-4511-9dbc-c0c365c07be3)

**Comment by remittor** [comment]
Показ реального статуса ещё предстоит сделать.
А никто и не обещал, что ютуб будет работать без доп. настройки (хотя у многих заработало сразу).

**Comment by Vaccinator424** [comment]
> Показ реального статуса ещё предстоит сделать. А никто и не обещал, что ютуб будет работать без доп. настройки (хотя у многих заработало сразу).

В любом случае красавчик что сделал установку zapret с помощью пакетов, так намного удобнее. Ждём следующей версии

**Comment by qwez** [comment]
@remittor очень круто, спасибо! На мобилках сразу заработало, а на телевизоре не захотел. Tizen OS (Samsung), подключено по проводу, открываю youtube (приложение), сразу вылетает и появляется уведомление "Ошибка сети". Не подскажешь в какую сторону копнуть?

**Comment by p0gran** [comment]
Xiaomi AIoT Router AX3600, установил всё по инструкции, запроса списка /var/opkg-lists/openwrt‑packages не было, выбрал то что было: aarch64_cortex-a53, прошивка: OpenWrt 23.05.5 r24106-10cc5fcd00 / LuCI openwrt-23.05 branch git-24.264.56413-c7a3562, нулевые изменения, установил так же Tune‐up DNS‐over‐HTTPS, тоже самое, ноль. Провайдер Ростелеком Сибирь.
с Новым "Launcher for zapret" от TOPERSOFT всё прекрасно работает. Не понимаю куда копать. Роутер был перед выполнением действий сброшен в ноль. Так же он является по сути маршрутизатором, так как ip получает гигабитка от ростелекома.

**Comment by remittor** [comment]
> Провайдер Ростелеком Сибирь.
> с Новым "Launcher for zapret" от TOPERSOFT всё прекрасно работает. Не понимаю куда копать.

Посмотрите какие параметры используются при запуске процесса winws.exe
И такие же настройки введите в OpenWrt модуле.

**Comment by p0gran** [comment]
К сожалению мозгов разобраться так и не хватило что куда :-(
Служба запускается с такими параметрами:
winws.exe  --wf-tcp=80,443 --wf-udp=443,50000-50099 --filter-udp=443 --hostlist="E:\Program Files\Zapret\youtube.txt" --dpi-desync=fake --dpi-desync-repeats=4 --dpi-desync-fake-quic="E:\Program Files\Zapret\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="E:\Program Files\Zapret\youtube.txt" --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-ttl=4 --new --filter-tcp=443 --hostlist="E:\Program Files\Zapret\youtube.txt" --dpi-desync=fake,split2 --dpi-desync-split-seqovl=2 --dpi-desync-split-pos=3 --dpi-desync-fake-tls="E:\Program Files\Zapret\tls_clienthello_www_google_com.bin" --dpi-desync-ttl=3 --new --filter-tcp=80 --hostlist="E:\Program Files\Zapret\blacklist.txt" --dpi-desync=fake,split2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist="E:\Program Files\Zapret\blacklist.txt" --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls="E:\Program Files\Zapret\tls_clienthello_www_google_com.bin" --dpi-desync-ttl=5 --new --filter-udp=443 --hostlist="E:\Program Files\Zapret\discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=8 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="E:\Program Files\Zapret\quic_initial_www_google_com.bin" --new --filter-udp=50000-50099 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=n1 --dpi-desync-fake-quic="E:\Program Files\Zapret\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="E:\Program Files\Zapret\discord.txt" --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls="E:\Program Files\Zapret\tls_clienthello_www_google_com.bin" --dpi-desync-ttl=5
