### ISSUE TITLE
Comments in lists

### ISSUE THREAD

**Issue by naabtog** [remittor/zapret-openwrt#30]
Как можно комментировать записи в списках? Например, если нужно временно исключить домен для проверки, но не хочется удалять совсем.

**Comment by remittor** [comment]
> Как можно комментировать записи в списках?

Наверное знак решётки поможет.
Но советую уточнить у bolvan'а.

**Comment by naabtog** [comment]
Самое простое [решение](https://github.com/bol-van/zapret/issues/476#issuecomment-2405717573) оказалось верным.

> Если первый символ на строке # ; / или строка пустая, хост не заносится в лист
