### ISSUE TITLE
ERROR: unable to select packages

### ISSUE THREAD

**Issue by geak** [remittor/zapret-openwrt#38]
Невозможно обновлять пакеты или просто устанавливать любые другие. Всегда приходится сначала удалять zapret.

```
# apk upgrade
ERROR: unable to select packages:
  zapret-69.20241206:
    error: uninstallable
    arch: aarch64_generic
    satisfies: world[zapret><Q1urM6NvAImRNp+r9fcjB4cnIT/+I=] luci-app-zapret-69.20241206-r1[zapret]
```

Установка zapret производится из [zapret_v69-20241206_aarch64_generic.zip](https://github.com/remittor/zapret-openwrt/releases/download/v69-20241206-23.05/zapret_v69-20241206_aarch64_generic.zip).

```
# ubus call system board
{
	"kernel": "6.6.63",
	"hostname": "geak",
	"system": "ARMv8 Processor rev 4",
	"model": "Bananapi BPi-R3 Mini",
	"board_name": "bananapi,bpi-r3-mini",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "OpenWrt",
		"version": "SNAPSHOT",
		"revision": "r28277-59dd9cddf9",
		"target": "mediatek/filogic",
		"description": "OpenWrt SNAPSHOT r28277-59dd9cddf9",
		"builddate": "1733771443"
	}
}
```

**Comment by remittor** [comment]
> Установка zapret производится из zapret_v69-20241206_aarch64_generic.zip

А зачем вы пытаетесь на SNAPSHOT установить ipk-файлы? Нужно брать apk-файлы для этого.

> # apk upgrade
>     error: uninstallable

Вот тут я не подскажу в чём трабла.

**Comment by geak** [comment]
> А зачем вы пытаетесь на SNAPSHOT установить ipk-файлы? Нужно брать apk-файлы для этого.

А как я установлю ipk через apk?

APK есть только в generic, в a53 их нет. Либо я криво смотрю..

**Comment by geak** [comment]
Что-то странное..
Я точно видел, что в generic есть apk, а в a53 их не было.

![IMG_3556](https://github.com/user-attachments/assets/50f89010-7649-4ba5-9698-7463c4424bea)
![IMG_3557](https://github.com/user-attachments/assets/ba0412a8-57c2-4191-b4a8-760e2ae35b82)

**Comment by remittor** [comment]
> APK есть только в generic, в a53 их нет. Либо я криво смотрю..

Криво смотрите!
Вот для Snapshot: https://github.com/remittor/zapret-openwrt/releases/download/v69-20241206-SNAPSHOT/zapret_v69-20241206_aarch64_cortex-a53.zip

**Comment by geak** [comment]
Аааа, SNAPSHOT! Спасибо, что выпрямили!

**Comment by nexsys14** [comment]
> > APK есть только в generic, в a53 их нет. Либо я криво смотрю..
> 
> Криво смотрите! Вот для Snapshot: https://github.com/remittor/zapret-openwrt/releases/download/v69-20241206-SNAPSHOT/zapret_v69-20241206_aarch64_cortex-a53.zip

@remittor Друг, что случилось со снапшотами? Ссылка не работает, в репозиториях их тоже нет.
