### ISSUE TITLE
Когда появится сборка под установщик apk?

### ISSUE THREAD

**Issue by dx4321** [remittor/zapret-openwrt#40]
Когда появится сборка под установщик apk?

Добрый день. Я обновил свой opewrt snapshot на моем Xiaomi router x3000t и теперь там ставятся только apk а не opkg методом. Если уже есть способ как можно установить вашу версию запрета то было бы здорово узнать об этом

**Comment by dx4321** [comment]
При попытке установить из веб люси по инструкции получаю следующее

Executing package manager
apk add /tmp/upload.apk
Errors
ERROR: /tmp/upload.apk: UNTRUSTED signature
The apk install command failed with code 99.

**Comment by remittor** [comment]
Это такое ограничение ввели разрабы OpenWrt для офиц сборок.
В офиц. сборках APK-файлы можно установить только через консольную команду.

**Comment by dx4321** [comment]
А как? Можешь дать инструкцию или что нибудь. А то таких как я будет все больше. 

Как минимум из-за того что на многие роутеры лучше ничего не ставить кроме официальных сборок (в моем случае снапшот только могу поставить)

Как бы да линукс это все классно, но к сожалению у меня как хомяка в этом вопросе не особо много вариантов кроме тех что рекомендуются на официальных форумах

**Comment by vandosik** [comment]
Я вот сейчас столкнулся с такой же проблемой. Перенес файлы из архива вручную на роутер и пытаюсь установить руками. Что то странное происходит.
```
root@OpenWrt:/tmp# apk verify zapret_69.20241206_mipsel_24kc
zapret_69.20241206_mipsel_24kc: No such file or directory
root@OpenWrt:/tmp# apk verify zapret_69.20241206_mipsel_24kc.ipk
zapret_69.20241206_mipsel_24kc.ipk: UNTRUSTED signature
root@OpenWrt:/tmp#
root@OpenWrt:/tmp# apk add --allow-untrusted zapret_69.20241206_mipsel_24kc.ipk
ERROR: unable to select packages:
  zapret_69.20241206_mipsel_24kc.ipk (no such package):
    required by: world[zapret_69.20241206_mipsel_24kc.ipk]
root@OpenWrt:/tmp# apk add --allow-untrusted /tmp/zapret_69.20241206_mipsel_24kc.ipk
ERROR: unable to select packages:
  /tmp/zapret_69.20241206_mipsel_24kc.ipk (no such package):
    required by: world[/tmp/zapret_69.20241206_mipsel_24kc.ipk]
```

**Comment by dx4321** [comment]
Я могу ошибаться но кажется, что нужно просто сделать загрузчик под apk, из пакетов исходного кода но как это делать я пока что не знаю

**Comment by remittor** [comment]
> пытаюсь установить руками. Что то странное происходит

Так нужно ставить не ipk, а apk.
Скачайте правильный zip.

**Comment by vandosik** [comment]
Точно, спасибо
Не обратил внимания, что есть SNAPSHOT релиз с apk.
Для него загрузка пошла 
```
apk add --allow-untrusted zapret-69.20241206.apk
fetch https://downloads.openwrt.org/snapshots/targets/ramips/mt7620/packages/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/packages.adb
fetch https://downloads.openwrt.org/snapshots/targets/ramips/mt7620/kmods/6.6.65-1-0782eedef0e2b1cb08ee73942ae726d0/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/routing/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/telephony/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/video/packages.adb
```

**Comment by vandosik** [comment]
@dx4321, у меня не хватило места на роутере, но это уже чисто моя проблема
В остальном руками не очень долго получается.
Надо подлючиться к роутеру по ssh
```
ssh root@openwrt.lan
```
На роутере необходимо установить sftp сервер, чтобы передать ему файлы
```
apk add openssh-sftp-server
```
Дальше можно установить [WinSCP](https://openwrt.org/docs/guide-quick-start/sshadministration#winscp), подключиться к роутеру и скопировать туда необходимые апкшки.
Далее на роутере руками установить
```
apk add --allow-untrusted zapret-69.20241206.apk
```

**Comment by dx4321** [comment]
я сделал инструкцию для чейников вроде мен


**Инструкция по установке модуля zapret-openwrt через APK-файлы на роутер с OpenWrt (для начинающих)**

**Важное замечание:** **На данный момент** данная инструкция применима только к **тестовым сборкам OpenWrt (snapshot)** и **будущим версиям после 23.05**, в которых используется пакетный менеджер `apk`. В **стабильной версии OpenWrt 23.05** используется пакетный менеджер `opkg`, и установка пакетов через APK-файлы невозможна. Если вы используете OpenWrt 23.05, вам нужно устанавливать модуль `zapret-openwrt` через `opkg`. Инструкцию по установке через `opkg` можно найти на странице проекта: [https://github.com/remittor/zapret-openwrt/wiki/Installing-zapret%E2%80%90openwrt-package](https://github.com/remittor/zapret-openwrt/wiki/Installing-zapret%E2%80%90openwrt-package)

**Что нам понадобится:**

*   Компьютер с Windows.
*   Архив с APK-файлами модуля `zapret-openwrt`, подходящий для архитектуры нашего роутера. **Ссылка на архив: [https://github.com/remittor/zapret-openwrt/releases](https://github.com/remittor/zapret-openwrt/releases)**
*   Программа WinSCP (для передачи файлов на роутер): [https://winscp.net/](https://winscp.net/)
*   Программа PuTTY (для подключения к роутеру по SSH): [https://www.chiark.greenend.org.uk/~sgtatham/putty/](https://www.chiark.greenend.org.uk/~sgtatham/putty/)
*   Доступ к веб-интерфейсу роутера (LuCI).

**Шаги:**

1. **Скачивание архива:**
    *   Скачиваем ZIP-архив, содержащий **APK-файлы** модуля `zapret-openwrt`, по ссылке: **[https://github.com/remittor/zapret-openwrt/releases](https://github.com/remittor/zapret-openwrt/releases)**
    *   **Чтобы определить архитектуру, подключаемся к роутеру по SSH (как описано в шаге 7) и выполняем команду:**

        ```bash
        uname -m
        ```

        Эта команда выведет название архитектуры, например, `armv7l`, `mips`, `x86_64` и т.д. На странице релизов ищем архив, собранный именно для этой архитектуры (обычно в названии архива присутствует название архитектуры).

2. **Распаковка архива:**
    *   Распаковываем скачанный ZIP-архив в любую папку на нашем компьютере.
    *   Нам нужны файлы `luci-app-zapret-*.apk` и `zapret-*.apk` (расширение `.apk` и имя файла может отличаться, главное, чтобы в названии присутствовало "zapret"). Остальные файлы из архива нам не понадобятся.

3. **Установка WinSCP:**
    *   Скачиваем и устанавливаем программу WinSCP по ссылке: [https://winscp.net/](https://winscp.net/)

4. **Подключение к роутеру через WinSCP:**
    *   Запускаем WinSCP.
    *   В окне "Новое подключение" выбираем:
        *   **Протокол:** `SCP`
        *   **Имя хоста:** IP-адрес нашего роутера (обычно `192.168.1.1`, но может отличаться; проверим в документации к роутеру или в настройках сети).
        *   **Имя пользователя:** `root` (или имя пользователя с правами администратора на роутере).
        *   **Пароль:** пароль администратора роутера (тот же, что и для входа в веб-интерфейс LuCI).
    *   Нажимаем "Войти".
    *   Если мы подключаемся к роутеру впервые, WinSCP может спросить о добавлении ключа хоста в кэш. Нажимаем "Да".

5. **Создание директории на роутере:**
    *   После успешного подключения мы увидим две панели: слева - файлы на нашем компьютере, справа - файлы на роутере.
    *   В правой панели (на роутере) переходим в директорию `/tmp`.
    *   Создаем в ней еще одну директорию с именем `tmp`. Для этого нажимаем правой кнопкой мыши в пустом месте правой панели, выбираем "Новый" -> "Каталог..." и вводим имя `tmp`.

6. **Копирование APK-файлов на роутер:**
    *   В левой панели WinSCP (на нашем компьютере) находим папку, в которую мы распаковали архив с APK-файлами.
    *   Выбираем нужные **APK-файлы** (`luci-app-zapret-*.apk` и `zapret-*.apk`).
    *   Перетаскиваем их мышкой из левой панели в правую панель в директорию `/tmp/tmp` на роутере.

7. **Установка PuTTY и подключение к роутеру по SSH:**
    *   Скачиваем и устанавливаем программу PuTTY по ссылке: [https://www.chiark.greenend.org.uk/~sgtatham/putty/](https://www.chiark.greenend.org.uk/~sgtatham/putty/)
    *   Запускаем PuTTY.
    *   В поле "Host Name (or IP address)" вводим IP-адрес нашего роутера.
    *   Убеждаемся, что выбран тип соединения "SSH" (порт `22`).
    *   Нажимаем "Open".
    *   Если мы подключаемся к роутеру впервые, PuTTY может спросить о добавлении ключа хоста в кэш. Нажимаем "Accept".
    *   В открывшемся окне терминала вводим имя пользователя `root` (или наше имя пользователя с правами администратора) и нажимаем `Enter`.
    *   Затем вводим пароль администратора роутера и нажимаем `Enter` (при вводе пароль не отображается).

8. **Установка APK-файлов:**
    *   После успешного входа в систему, переходим в директорию, куда мы скопировали APK-файлы, с помощью команды:

        ```bash
        cd /tmp/tmp
        ```

    *   Затем устанавливаем **APK-файлы** по очереди, используя команду `apk add --allow-untrusted` для каждого файла. Например:

        ```bash
        apk add --allow-untrusted zapret-v0.4.10.apk
        ```

        ```bash
        apk add --allow-untrusted luci-app-zapret_v0.4.10-1_all.apk
        ```

        **Важно:** Флаг `--allow-untrusted` используем для установки неподписанных APK-пакетов. Вместо `zapret-v0.4.10.apk` и `luci-app-zapret_v0.4.10-1_all.apk` подставляем актуальные имена файлов, которые мы скачали из архива.

9. **Перезагрузка интерфейса LuCI (логаут):**
    *   **Делаем логаут в веб-интерфейсе LuCI на 6 секунд.** Затем логинимся снова.

10. **Удаление временной директории:**
    *   **Чтобы освободить память роутера, удаляем временную директорию `/tmp/tmp` с APK-файлами.** Для этого выполняем команду:

        ```bash
        rm -rf /tmp/tmp
        ```

**После установки:**

*   Если мы устанавливали плагин для LuCI, он должен появиться в соответствующем разделе веб-интерфейса.
*   Проверяем работу установленного модуля `zapret-openwrt`.

**Дополнительные замечания:**

*   Вместо создания `/tmp/tmp` можно использовать любую другую временную директорию.

**Comment by dx4321** [comment]
Наверное можно добавить инструкцию в redmi https://github.com/remittor/zapret-openwrt если устраивает

**Comment by koldyn98** [comment]
всем привет, использовал вашу инструкцию, и мне он выдает  что пакета такого нет 

![Image](https://github.com/user-attachments/assets/8a904b3e-8959-4046-8cc1-1749cbf708e9)

**Comment by remittor** [comment]
У вас ошибка в ".cd /tmp/tmp" - точка не нужна!
